[build]
  base = "/"
  publish = "client/dist"
  # Change the command to ensure npm install runs in client before build
  command = "npm install --prefix client && npm run build --prefix client" 

[functions]
  directory = "api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200